import { StyleSheet } from 'react-native';
import { BRAND } from '@/constants/moods';

/** Card and control styling shared by the mood insight and reminder panels. */
export const panelStyles = StyleSheet.create({
  section: { paddingHorizontal: 16, paddingTop: 8 },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: '#E7ECF1',
  },
  cardTitle: { fontSize: 16, fontWeight: '800', color: '#1C242C' },
  cardSubtitle: { fontSize: 12, color: '#7A828C', fontWeight: '600', marginTop: 2 },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 14,
  },
  rowBetween: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  bigStat: { fontSize: 30, fontWeight: '800', color: '#1C242C' },
  statUnit: { fontSize: 13, fontWeight: '700', color: '#8B949E' },
  statGrid: { flexDirection: 'row', flexWrap: 'wrap', marginTop: 4 },
  statBox: { width: '50%', paddingVertical: 8 },
  statLabel: { fontSize: 11, color: '#8B949E', fontWeight: '700', textTransform: 'uppercase' },
  statValue: { fontSize: 18, fontWeight: '800', color: '#1C242C', marginTop: 2 },
  muted: { color: '#7A828C', fontSize: 12, fontWeight: '600' },
  empty: { color: '#7A828C', textAlign: 'center', paddingVertical: 14, fontSize: 13 },
  error: { color: '#BA1A1A', fontSize: 13, marginBottom: 10 },
  divider: { height: StyleSheet.hairlineWidth, backgroundColor: '#E7ECF1', marginVertical: 12 },

  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: {
    paddingHorizontal: 12,
    paddingVertical: 7,
    borderRadius: 16,
    backgroundColor: '#EEF3F7',
  },
  chipActive: { backgroundColor: BRAND },
  chipText: { fontSize: 12, fontWeight: '700', color: '#5B6570' },
  chipTextActive: { color: '#FFFFFF' },

  primaryButton: {
    backgroundColor: BRAND,
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
  },
  primaryText: { color: '#FFFFFF', fontWeight: '800', fontSize: 14 },
  secondaryButton: {
    borderRadius: 12,
    paddingVertical: 13,
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    gap: 8,
    borderWidth: 1,
    borderColor: BRAND,
    backgroundColor: '#FFFFFF',
  },
  secondaryText: { color: BRAND, fontWeight: '800', fontSize: 14 },
  buttonRow: { flexDirection: 'row', gap: 10 },
  flex1: { flex: 1 },
  disabled: { opacity: 0.55 },

  input: {
    backgroundColor: '#F3F5F7',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 11,
    color: '#1C242C',
    fontSize: 14,
  },
  inputLabel: {
    fontSize: 11,
    fontWeight: '800',
    color: '#8B949E',
    textTransform: 'uppercase',
    marginBottom: 6,
    marginTop: 12,
  },

  listRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
    paddingVertical: 10,
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#EDF1F5',
  },
  listTitle: { fontSize: 14, fontWeight: '700', color: '#1C242C' },
  listMeta: { fontSize: 11, color: '#8B949E', fontWeight: '600', marginTop: 2 },

  modalBackdrop: { flex: 1, backgroundColor: 'rgba(0,0,0,0.35)', justifyContent: 'flex-end' },
  modalCard: {
    backgroundColor: '#FFFFFF',
    padding: 20,
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    maxHeight: '90%',
  },
  cancelButton: { alignItems: 'center', paddingVertical: 12 },
});
